### ISSUE TITLE
stdio vs io

### ISSUE THREAD

**Issue by bubnenkoff** [jasonwhite/io#5]
Do you have any plans to add it for review as stdio candidate replacement? Could you write about it's benefits on stdio?

**Comment by jasonwhite** [comment]
I don't have any plans to propose it as an `std.stdio` replacement in the near future. I think it needs more polishing first. It may eventually happen and it would be a big breaking change. It would likely go in as `std.io` and `std.stdio` would be deprecated for several years until removed for good.

The main benefits for me over `std.stdio` are:
- Generic stream interfaces.
- [Opening many files in parallel on Windows doesn't deadlock or crash](https://issues.dlang.org/show_bug.cgi?id=13727). (Two years later, this bug still hasn't been fixed. :disappointed:)
- Low overhead by using read/write system calls.
- The API is more robust and pleasant to use.

**Comment by bubnenkoff** [comment]
Could you explain what is stream? There was old realiation in D that was
deprecated. But what is it. Where it handful?

четверг, 23 июня 2016 г. пользователь Jason White написал:

**Comment by jasonwhite** [comment]
To use the terminology in the library, a stream is either a _source_ or a _sink_. A _source_ is simply a struct/class with a `read()` method and a _sink_ is simply a struct/class with a `write()` method. A stream can be either a source, sink, or both. Streams are also optionally _seekable_. Such is the case with files, but not pipes.

A stream is similar in concept to D's ranges. The main difference is that you can read or write many elements at a time with streams. Furthermore, reads and writes are destructive for streams, meaning that the stream is mutated because the position in the stream is advanced how ever many elements were read/written.

Ranges can also be implemented on top of streams efficiently (but not the other way around). This is useful if you want to use the wonderful range operations (like `map`, `filter`, etc.) in `std.algorithm`.

**Comment by bubnenkoff** [comment]
Big thanks! Please add this info to readme

четверг, 23 июня 2016 г. пользователь Jason White написал:
